### ISSUE TITLE
Not working anymore?

### ISSUE THREAD

**Issue by MetroAffe** [jodur/imagesdirectory-camera#5]
Since I updated to 2022.4
Anyone else with same Problem?
![26FAC517-67B5-47E9-9BC1-06E32B4388DD](https://user-images.githubusercontent.com/61084462/163679905-1952ffe6-00ba-40c9-99c6-e41acc19e16a.jpeg)

**Comment by jodur** [comment]
I am the developer of the plugin and i am On 2022.4.5 and didn’t had any problems with either the previous versions.

**Comment by MetroAffe** [comment]
Okay. I‘m not sure if the update brings this new option or it was just reset through it
![8D203253-3B30-40BA-8CE7-EC2D5E1EAD23](https://user-images.githubusercontent.com/61084462/163693256-c6b8283b-d218-4361-ba81-6b4c363da0df.jpeg)
. So the solution was to reselect „live“. Now its working again
